Repository travel-service/frontend, pull requests merged in 2022-08, with the labels that each got.

#8 Design&Feat: 너비, 높이 조정 및 세부 디자인 요소 추가, Header 기능 수정
  src/components/Canvas/BuildTab/Dnd/SelLocBasket.js
  src/components/Canvas/common/CanvasForm.js
  src/components/Landing/Header.js
  src/components/Landing/LandingMainContents.js
  src/components/Landing/UseWays.js
  src/components/common/PageTemplate.js
  src/containers/common/HeaderContainer.js
  src/lib/styles/palette.js
  src/pages/OtherPages/LandingPage.js
  src/pages/OtherPages/SearchPage.js
Labels: 디자인, 기능 수정

#9 Design: Auth 폼 디자인 수정
  public/images/logoLetterV2.png
  public/images/logoPaintingV2.png
  src/components/Auth/AuthForm.js
  src/components/Auth/AuthTemplate.js
  src/components/Landing/Logo.js
  src/components/common/Button.js
  src/lib/api/plan.js
  src/lib/zustand/planStore.js
Labels: 디자인

#10 Feat&Refactor: auth관련 api 수정 및 회원가입 검증 기능 추가
  src/components/Auth/AuthForm.js
  src/components/Auth/AuthTemplate.js
  src/containers/Auth/SignupForm.js
  src/lib/api/auth.js
  src/lib/interceptors/axios.js
  src/lib/redux/modules/auth.js
  src/lib/redux/modules/user.js
Labels: 디자인, 기능 추가, 기능 수정

#11 Merge develop into main
  public/images/logoLetterV2.png
  public/images/logoPaintingV2.png
  src/components/Auth/AuthForm.js
  src/components/Auth/AuthTemplate.js
  src/components/Canvas/BuildTab/Dnd/Days.js
  src/components/Canvas/BuildTab/Dnd/PlanDays.js
  src/components/Canvas/BuildTab/Dnd/SelLocBasket.js
  src/components/Canvas/BuildTab/LocDetail/DayHeader.js
  src/components/Canvas/BuildTab/LocDetail/Location.js
  src/components/Canvas/BuildTab/LocDetail/MoveDataDiv.js
  src/components/Canvas/BuildTab/MainArea.js
  src/components/Canvas/common/CanvasButtons.js
  src/components/Canvas/common/CanvasForm.js
  src/components/Canvas/common/ProcessBar.js
  src/components/Landing/Header.js
  src/components/Landing/LandingMainContents.js
  src/components/Landing/Logo.js
  src/components/Landing/UseWays.js
  src/components/common/Button.js
  src/components/common/PageTemplate.js
  src/containers/Auth/SignupForm.js
  src/containers/Canvas/BuildBlockForm.js
  src/containers/Canvas/TravelCheckForm.js
  src/containers/common/HeaderContainer.js
  src/lib/Icons/Time.js
  src/lib/api/auth.js
  src/lib/api/plan.js
  src/lib/interceptors/axios.js
  src/lib/redux/modules/auth.js
  src/lib/redux/modules/user.js
  src/lib/styles/palette.js
  src/lib/zustand/planStore.js
  src/pages/CanvasPages/CanvasMainPage.js
  src/pages/CanvasPages/TravelCheckPage.js
  src/pages/OtherPages/LandingPage.js
  src/pages/OtherPages/SearchPage.js
Labels: 디자인, 기능 추가, 리팩토링, 기능 수정

#13 Refactor&Design: 회원가입, 로그인 디자인 작업에 맞춰 수정, 리팩토링
  src/components/Auth/AuthForm.js
  src/components/Auth/AuthTemplate.js
  src/lib/api/location.js
Labels: 디자인, 리팩토링

#15 Merge develop into main
  src/App.js
  src/components/Auth/AuthForm.js
  src/components/Auth/AuthTemplate.js
  src/components/Canvas/BuildTab/Dnd/PlanDays.js
  src/components/Canvas/common/CanvasButtons.js
  src/components/Canvas/common/CanvasForm.js
  src/components/Canvas/common/CanvasTemplate.js
  src/containers/Canvas/Block.js
  src/containers/Canvas/BuildBlockForm.js
  src/containers/Canvas/TravelCheckForm.js
  src/lib/api/location.js
  src/lib/interceptors/axios.js
  src/lib/zustand/memberLocStore.js
  src/lib/zustand/planStore.js
  src/pages/CanvasPages/CanvasMainPage.js
  src/pages/CanvasPages/SelectBlockPage.js
  src/pages/CanvasPages/TravelCheckPage.js
  src/pages/CanvasPages/TravelSettingPage.js
  src/pages/CanvasPages/TravelSharePage.js
Labels: 디자인, 기능 추가, 리팩토링, 기능 수정

#18 Fix: 로그인 권한 버그 수정
  src/lib/api/auth.js
  src/lib/router/ProtectedRoute.js
  src/pages/CanvasPages/CanvasMainPage.js
Labels: 리팩토링, 버그 수정

#21 My page
  src/components/My/MyHeader.js
  src/components/My/MyInfo/MyInfo.js
  src/components/My/MySetting/MyEdit.js
  src/components/My/MySetting/MyPasswd.js
  src/components/My/img/profile.jpg
  src/components/My/img/profile2.jpg
  src/components/Notice/Search.js
  src/lib/api/my.js
  src/lib/zustand/myStore.js
  src/pages/MyPages/MyInfoPage.js
  src/pages/MyPages/MySettingPage.js
Labels: 버그 수정
